services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: esbla
      POSTGRES_PASSWORD: esbla
      POSTGRES_USER: esbla
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esbla -d esbla"]
      interval: 2s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - esbla-postgres:/var/lib/postgresql/data

volumes:
  esbla-postgres:
